# Generated by Django 2.1.7 on 2019-02-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spots_empty', models.IntegerField(default=0)),
                ('spots_occupied', models.IntegerField(default=0)),
                ('spots_total', models.IntegerField(default=0)),
            ],
        ),
    ]
